### ISSUE TITLE
Remove duplicate peers from the list when creating a channel

### ISSUE THREAD

**Issue by janb87** [Kunstmaan/hyperledger-fabric-client-utils#3]
Currently it fails on a dev setup when you use the same peer url many times

**Comment by janb87** [comment]
[2018-02-02T16:57:25.507] [ERROR] lib/invoke - Failed to invoke successfully: {"name":"DuplicatePeer","message":"Peer with URL grpc://localhost:7051 already exists"}

**Comment by brunus0475** [comment]
How Could I solve It?

**Comment by brunus0475** [comment]
I have a Nodejs+Express application that use a controller.js to comunicate with the blockchain. The first transaction is good, the next fails with the following error "[Channel.js]: Peer xxxx already exists". If I restart the app.js, the situation is the same (only the first transaction works fine).
